#!/bin/bash



echo "Compilation starts...."
for f in *.c;do 
    gcc  "f"
done
echo "Compilation done..."
echo "Merging dot files"
gcc *.o myprogram

echo "-----------x-------------"
echo "Compilation complete"
